# Generated by Django 3.1.1 on 2021-05-10 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('option_1', models.CharField(max_length=500)),
                ('option_2', models.CharField(max_length=500)),
                ('option_3', models.CharField(max_length=500)),
                ('option_4', models.CharField(max_length=500)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('number_of_questions', models.IntegerField(default=10)),
                ('questions', models.ManyToManyField(to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_id', models.CharField(default='', max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
