# Generated by Django 3.1.1 on 2021-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_history_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
