# Generated by Django 3.1.1 on 2021-05-13 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210513_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
