# Generated by Django 3.1.1 on 2021-05-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_history_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='data',
            new_name='date',
        ),
    ]
